In [1]:
import pandas as pd
import numpy as np
import sklearn as skl
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('../data/merged_data.csv', dtype={'FIPS': object})

In [3]:
list(data.columns)

['Unnamed: 0',
 'FIPS',
 'State',
 'County',
 'Deaths',
 'Years of Potential Life Lost Rate',
 '% Fair or Poor Health',
 'Average Number of Physically Unhealthy Days',
 'Average Number of Mentally Unhealthy Days',
 '% Low Birthweight',
 '% Smokers',
 'Food Environment Index',
 '% Physically Inactive',
 '% With Access to Exercise Opportunities',
 '% Excessive Drinking',
 '% Driving Deaths with Alcohol Involvement',
 'Chlamydia Rate',
 'Teen Birth Rate',
 'Primary Care Physicians Rate',
 'Dentist Rate',
 '% With Annual Mammogram',
 '% Vaccinated',
 'High School Graduation Rate',
 '% Some College',
 '% Unemployed',
 '% Children in Poverty',
 'Income Ratio',
 '% Single-Parent Households',
 'Social Association Rate',
 'Violent Crime Rate',
 'Injury Death Rate',
 'Average Daily PM2.5',
 'Presence of Water Violation',
 '% Severe Housing Problems',
 '% Drive Alone to Work',
 '% Long Commute - Drives Alone',
 'Life Expectancy',
 'Age-Adjusted Death Rate',
 'Child Mortality Rate',
 'Infant Mortality Rate',
 '% Frequent Mental Distress',
 'HIV Prevalence Rate',
 '% Food Insecure',
 '% Limited Access to Healthy Foods',
 'Drug Overdose Mortality Rate',
 'Motor Vehicle Mortality Rate',
 '% Insufficient Sleep',
 '% Children Uninsured',
 'Other Primary Care Provider Ratio',
 '% Disconnected Youth',
 'Average Reading Performance',
 'Average Math Performance',
 'Median Household Income',
 '% Enrolled in Free or Reduced Lunch',
 'Black/White Segregation Index',
 'non-White/White Segregation Index',
 'Homicide Rate',
 'Suicide Rate (Age-Adjusted)',
 'Firearm Fatalities Rate',
 'Juvenile Arrest Rate',
 '% Homeowners',
 '% Severe Housing Cost Burden',
 'Population',
 '% less than 18 years of age',
 '% Black',
 '% American Indian & Alaska Native',
 '% Asian',
 '% Native Hawaiian/Other Pacific Islander',
 '% Hispanic',
 '% Non-Hispanic White',
 '% Not Proficient in English',
 '% Female',
 '% Rural',
 'countycode',
 'internet_consumer',
 'internet_nonconsumer',
 'internet_all',
 'internet_hhs',
 'internet_ratio',
 'covid_cases',
 'covid_deaths',
 'internet_percent',
 '%  Adults with Obesity',
 'Heart Disease Death Rate',
 'Hypertension Death Rate',
 '% Adults 65 and Older',
 'COPD Mortality Rate',
 '% Diagnosed Diabetes',
 '% Nonwhite',
 '% households wo car',
 'Number of Hospitals',
 '% disabled',
 '% Without Health Insurance',
 '% Limited English Proficiency',
 '% workers commuting by public transit',
 '% Veterans in Civilian Adult Population',
 'Opioid Death Rate']

In [4]:
scores=pd.read_csv('../data/scores.csv', dtype={'FIPS': object})

In [5]:
scores.head()

,FIPS,State,County,severe_cases,food_services,community,mental_health,mobile_health,overwhelm,info
0,01003,Alabama,Baldwin,46.094118,47.389706,46.523109,62.009804,56.291757,48.643791,59.007353
1,01043,Alabama,Cullman,75.764706,47.573529,49.117647,69.101307,50.162345,62.561275,13.088235
2,01055,Alabama,Etowah,77.400000,68.161765,41.670168,55.947712,61.242658,65.702614,16.727941
3,01073,Alabama,Jefferson,55.688235,68.198529,46.796218,50.359477,61.368020,56.907680,35.477941
4,01089,Alabama,Madison,59.332353,50.122549,45.178571,59.771242,52.989717,50.980392,52.316176

### Severe COVID Complications

In [6]:
severe=scores[['FIPS','State','County','severe_cases']].copy()

In [8]:
severe=severe.merge(data[['covid_cases','% Adults 65 and Older','% Diagnosed Diabetes','%  Adults with Obesity',
                          'Heart Disease Death Rate','Hypertension Death Rate','COPD Mortality Rate',
                          '% Smokers','FIPS']], on='FIPS')

In [9]:
severe=severe.rename(columns={'severe_cases':'Severe COVID Case Complications'})

In [10]:
severe.head()

,FIPS,State,County,Severe COVID Case Complications,covid_cases,% Adults 65 and Older,% Diagnosed Diabetes,% Adults with Obesity,Heart Disease Death Rate,Hypertension Death Rate,COPD Mortality Rate,% Smokers
0,01003,Alabama,Baldwin,46.094118,6995,20.978,8.2,30.1,362.6,143.4,45.27,17.489033
1,01043,Alabama,Cullman,75.764706,2915,18.784,13.3,35.6,507.6,211.3,81.58,17.901071
2,01055,Alabama,Etowah,77.400000,4578,19.357,14.8,35.9,531.9,192.2,88.44,20.147399
3,01073,Alabama,Jefferson,55.688235,24754,16.297,11.5,34.4,369.8,155.4,48.44,17.622045
4,01089,Alabama,Madison,59.332353,9893,15.322,11.9,33.5,385.9,208.3,53.14,16.820173

In [11]:
severe.to_csv('../data/severe_cases_score_data.csv')

### Economic Harm

In [16]:
economic=scores[['FIPS','State','County','economic']].copy()

In [17]:
economic=economic.merge(data[['% Uninsured','% Children in Poverty','Income Ratio','% Single-Parent Households',
                             '% Severe Housing Cost Burden','% Severe Housing Problems',
                              '% Enrolled in Free or Reduced Lunch','% Unemployed','FIPS',
                             'High School Graduation Rate']], on='FIPS')

In [19]:
economic=economic.rename(columns={'economic':'Risk of Severe Economic Harm'})

In [20]:
economic.head()

,FIPS,State,County,Risk of Severe Economic Harm,% Uninsured,% Children in Poverty,Income Ratio,% Single-Parent Households,% Severe Housing Cost Burden,% Severe Housing Problems,% Enrolled in Free or Reduced Lunch,% Unemployed,High School Graduation Rate
0,01001,Alabama,Autauga,48.443354,11.148989,19.3,5.234597,26.242679,13.403481,14.663462,43.408673,3.629079,90.000000
1,01003,Alabama,Baldwin,40.330062,14.348525,13.9,4.417767,24.139601,11.725808,13.566201,48.486565,3.615382,86.361577
2,01005,Alabama,Barbour,75.368421,16.085834,43.9,5.681410,56.603426,14.059546,14.583333,63.292302,5.171384,81.410256
3,01007,Alabama,Bibb,48.314005,13.000000,27.8,4.368581,28.689236,9.886874,10.496454,61.562116,3.971828,83.763838
4,01009,Alabama,Blount,38.792150,17.082342,18.0,4.430262,28.561828,8.462257,10.548012,52.906287,3.511157,93.468795

In [21]:
economic.to_csv('../data/economic_score_data.csv')

### Mobile Health

In [12]:
mobile=scores[['FIPS','State','County','mobile_health']].copy()

In [24]:
mobile=mobile.merge(data[['% Smokers','% Rural','% households wo car','% workers commuting by public transit',
                          'Primary Care Physicians Rate''FIPS']], on='FIPS')

In [25]:
mobile=mobile.rename(columns={'mobile_health':'Need for Mobile Health Resources','% Uninsured_y':'% Uninsured',
                             'internet_percent':'% Home Internet Access'})

In [26]:
mobile.head()

,FIPS,State,County,Need for Mobile Health Resources,% Smokers,% Uninsured,% Adults with Obesity,% Adults with Diabetes,% 65 and over,Primary Care Physicians Rate,% Fair or Poor Health,% Home Internet Access
0,01001,Alabama,Autauga,45.449651,18.081557,11.148989,33.3,11.1,15.562670,45.04180,20.882987,75.0
1,01003,Alabama,Baldwin,39.710867,17.489033,14.348525,31.0,10.7,20.443350,72.89727,17.509134,92.0
2,01005,Alabama,Barbour,80.345962,21.999985,16.085834,41.7,17.6,19.420441,31.65809,29.591802,54.0
3,01007,Alabama,Bibb,55.455633,19.114200,13.000000,37.6,14.5,16.473214,48.52656,19.439724,69.8
4,01009,Alabama,Blount,72.906281,19.208672,17.082342,33.8,17.0,18.236515,22.40877,21.745293,62.0

In [27]:
mobile.to_csv('../data/mobile_health_score_data.csv')