In [1]:
import pandas as pd
import numpy as np
import sklearn as skl
from sklearn import preprocessing
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [3]:
#read in data
data=pd.read_csv('data/merged_data.csv', dtype={'FIPS': object})
data=data.drop(data.columns[0], axis=1)
data.head()

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Smokers,% Adults with Obesity,Food Environment Index,% Physically Inactive,% With Access to Exercise Opportunities,% Excessive Drinking,% Driving Deaths with Alcohol Involvement,Chlamydia Rate,Teen Birth Rate,% Uninsured_x,Primary Care Physicians Rate,Dentist Rate,% With Annual Mammogram,% Vaccinated,High School Graduation Rate,% Some College,% Unemployed,% Children in Poverty,Income Ratio,% Single-Parent Households,Social Association Rate,Violent Crime Rate,Injury Death Rate,Average Daily PM2.5,Presence of Water Violation,% Severe Housing Problems,% Drive Alone to Work,% Long Commute - Drives Alone,Life Expectancy,Age-Adjusted Death Rate,Child Mortality Rate,Infant Mortality Rate,% Frequent Mental Distress,% Adults with Diabetes,HIV Prevalence Rate,% Food Insecure,% Limited Access to Healthy Foods,Drug Overdose Mortality Rate,Motor Vehicle Mortality Rate,% Insufficient Sleep,% Uninsured_y,% Uninsured.1,Other Primary Care Provider Ratio,% Disconnected Youth,Average Grade Performance,Average Grade Performance.1,Median Household Income,% Enrolled in Free or Reduced Lunch,Segregation index,Segregation Index,Homicide Rate,Suicide Rate (Age-Adjusted),Firearm Fatalities Rate,Juvenile Arrest Rate,% Homeowners,% Severe Housing Cost Burden,Population,% less than 18 years of age,% 65 and over,% Black,% American Indian & Alaska Native,% Asian,% Native Hawaiian/Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Not Proficient in English,% Female,% Rural,countycode,internet_consumer,internet_nonconsumer,internet_all,internet_hhs,internet_ratio,date,county,state,fips,covid_cases,covid_deaths,internet_percent
0,01001,Alabama,Autauga,791.0,8128.591190,20.882987,4.743889,4.654031,8.619529,18.081557,33.3,7.2,34.7,69.130124,15.026031,26.785714,407.2,25.284927,8.721686,45.04180,32.37352,41.0,41.0,90.000000,62.009974,3.629079,19.3,5.234597,26.242679,12.071202,272.282220,68.526994,11.7,No,14.663462,86.523661,39.6,76.879477,417.547551,55.922156,7.940109,14.129347,11.1,219.1,13.2,11.991125,10.809447,19.328751,35.905406,11.148989,2.669154,2527:1,NaN,2.959586,2.802699,59338.0,43.408673,24.619138,23.628395,4.896617,18.145295,16.230078,10.625000,74.894625,13.403481,55601,23.674035,15.562670,19.343177,0.480207,1.224798,0.111509,2.965774,74.308016,0.820225,51.448715,42.002162,1001,16,1,17,21.054,0.75,2020-04-24,Autauga,Alabama,1001,36,2,75.0
1,01003,Alabama,Baldwin,2967.0,7354.122530,17.509134,4.224519,4.304056,8.345003,17.489033,31.0,8.0,26.5,73.713549,17.958310,30.769231,325.0,27.880692,11.333404,72.89727,49.53629,43.0,44.0,86.361577,67.371620,3.615382,13.9,4.417767,24.139601,10.205617,203.660396,72.385054,10.3,No,13.566201,84.282433,41.7,78.450258,353.343111,47.381750,5.546701,13.475336,10.7,166.5,11.6,5.424427,13.610487,15.811239,33.305868,14.348525,3.538763,1787:1,8.476795,3.005642,2.860696,57588.0,48.486565,41.271763,31.825343,3.008333,19.377511,14.093514,26.192661,73.619343,11.725808,218022,21.607911,20.443350,8.783976,0.772399,1.150343,0.066966,4.646779,83.111337,0.543517,51.538377,42.279099,1003,70,9,80,76.133,0.92,2020-04-24,Baldwin,Alabama,1003,147,3,92.0
2,01005,Alabama,Barbour,472.0,10253.573403,29.591802,5.430279,5.185594,11.474559,21.999985,41.7,5.6,23.5,53.166770,12.844016,40.000000,716.3,40.870815,12.242792,31.65809,36.17218,45.0,37.0,81.410256,34.857649,5.171384,43.9,5.681410,56.603426,7.518797,414.277861,70.274612,11.5,No,14.583333,83.368470,32.2,75.341935,497.350062,74.225274,NaN,16.586252,17.6,420.6,22.0,10.739667,NaN,22.854780,38.563167,16.085834,2.913534,1914:1,13.339302,2.660388,2.443271,34382.0,63.292302,25.039132,23.449713,7.618260,12.836104,17.761715,15.000000,61.397779,14.059546,24881,20.867328,19.420441,48.032635,0.659137,0.454162,0.184880,4.276355,45.641252,1.631683,47.216752,67.789635,1005,5,1,6,9.191,0.54,2020-04-24,Barbour,Alabama,1005,32,0,54.0
3,01007,Alabama,Bibb,471.0,11977.539484,19.439724,4.591482,4.551699,10.308710,19.114200,37.6,7.8,33.5,16.251364,15.570042,27.586207,339.7,41.696794,10.206253,48.52656,22.32143,40.0,38.0,83.763838,44.137353,3.971828,27.8,4.368581,28.689236,8.381860,89.349126,108.156028,11.2,No,10.496454,84.910647,49.8,73.571820,589.041117,85.800086,12.244898,14.017536,14.5,196.8,14.3,2.601627,28.060433,25.964321,38.148865,13.000000,2.617801,896:1,NaN,2.628688,2.381308,46064.0,61.562116,52.603794,52.600206,8.232590,20.858766,23.936170,NaN,75.073099,9.886874,22400,20.477679,16.473214,21.120536,0.437500,0.236607,0.116071,2.625000,74.589286,0.268210,46.781250,68.352607,1007,-9999,-9999,4,6.916,-9999.00,2020-04-24,Bibb,Alabama,1007,34,0,-999900.0
4,01009,Alabama,Blount,1085.0,11335.071134,21.745293,4.860808,4.891455,7.604563,19.208672,33.8,8.4,30.3,15.634486,14.230594,19.444444,234.4,33.534595,13.360759,22.40877,19.01798,34.0,39.0,93.468795,53.361073,3.511157,18.0,4.430262,28.561828,8.446383,482.690611,107.285369,11.7,No,10.548012,86.178362,59.4,74.145826,515.611823,83.798883,6.841993,14.859271,17.0,99.8,10.7,2.880150,24.199543,28.666962,35.945010,17.082342,4.077284,4449:1,18.941594,3.025407,2.849339,50412.0,52.906287,48.214823,17.694495,6.425353,17.062628,20.072746,7.460317,78.626214,8.462257,57840,23.153527,18.236515,1.462656,0.653527,0.319848,0.121024,9.571231,86.886238,1.724520,50.726141,89.951502,1009,13,1,14,20.690,0.62,2020-04-24,Blount,Alabama,1009,31,0,62.0

In [ ]:
# make a df of just quantified variables
data=data.drop(columns=['State'])

In [97]:
# make a function to create quantiles of columns

colname = lambda col, suffix: '{}_{}'.format(suffix, col)
def add_quantiles(data, columns, suffix, quantiles=4, labels=None):
    """ For each column name in columns, create a new categorical column with
        the same name as colum, with the suffix specified added, that
        specifies the quantile of the row in the original column using
        pandas.qcut().

        Input
        _____
        data:
            pandas dataframe
            columns:
            list of column names in `data` for which this function is to create
            quantiles
        suffix:
        string suffix for new column names ({`suffix`}_{collumn_name})
        labels:
            list of labels for each quantile (should have length equal to `quantiles`)
        Output
          ______
        pandas dataframe containing original columns, plus new columns with quantile
        information for specified columns.
        """
    d = data.copy()
    quantile_labels = labels or [
        '{:.0f}%'.format(i*100/quantiles) for i in range(1, quantiles+1)
    ]
    for column in columns:
        d[colname(column, suffix)] = d[column].rank(pct=True)
        #pd.qcut(d[column], quantiles, labels=quantile_labels)
    return d

In [98]:
cols=['Years of Potential Life Lost Rate', '% Fair or Poor Health', 'Average Number of Physically Unhealthy Days',
      'Average Number of Mentally Unhealthy Days', '% Low Birthweight', '% Smokers', '% Adults with Obesity',
      'Food Environment Index', '% Physically Inactive', '% With Access to Exercise Opportunities',
      '% Excessive Drinking', '% Driving Deaths with Alcohol Involvement', 'Chlamydia Rate', 'Teen Birth Rate',
      '% Uninsured_x', 'Primary Care Physicians Rate','Dentist Rate','% With Annual Mammogram','% Vaccinated',
      'High School Graduation Rate', '% Some College','% Unemployed','% Children in Poverty','Income Ratio',
      '% Single-Parent Households','Social Association Rate','Violent Crime Rate','Injury Death Rate',
      'Average Daily PM2.5','% Severe Housing Problems','% Drive Alone to Work','% Long Commute - Drives Alone',
      'Life Expectancy','Age-Adjusted Death Rate','Child Mortality Rate','Infant Mortality Rate',
      '% Frequent Mental Distress','% Adults with Diabetes','HIV Prevalence Rate','% Food Insecure',
      '% Limited Access to Healthy Foods','Drug Overdose Mortality Rate','Motor Vehicle Mortality Rate',
      '% Insufficient Sleep','% Uninsured_y','% Disconnected Youth','Average Grade Performance',
      'Average Grade Performance.1','Median Household Income','% Enrolled in Free or Reduced Lunch',
      'Segregation index','Segregation Index','Homicide Rate','Suicide Rate (Age-Adjusted)','Firearm Fatalities Rate',
      'Juvenile Arrest Rate','% Homeowners','% Severe Housing Cost Burden','Population','% less than 18 years of age',
      '% 65 and over','% Not Proficient in English',
      'internet_consumer','internet_all','internet_hhs','internet_ratio',
      'covid_cases']
data_q=add_quantiles(data, cols, 'q', 10)

In [99]:
data_q.head()

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Smokers,% Adults with Obesity,Food Environment Index,% Physically Inactive,% With Access to Exercise Opportunities,% Excessive Drinking,% Driving Deaths with Alcohol Involvement,Chlamydia Rate,Teen Birth Rate,% Uninsured_x,Primary Care Physicians Rate,Dentist Rate,% With Annual Mammogram,% Vaccinated,High School Graduation Rate,% Some College,% Unemployed,% Children in Poverty,Income Ratio,% Single-Parent Households,Social Association Rate,Violent Crime Rate,Injury Death Rate,Average Daily PM2.5,Presence of Water Violation,% Severe Housing Problems,% Drive Alone to Work,% Long Commute - Drives Alone,Life Expectancy,Age-Adjusted Death Rate,Child Mortality Rate,Infant Mortality Rate,% Frequent Mental Distress,% Adults with Diabetes,HIV Prevalence Rate,% Food Insecure,% Limited Access to Healthy Foods,Drug Overdose Mortality Rate,Motor Vehicle Mortality Rate,% Insufficient Sleep,% Uninsured_y,% Uninsured.1,Other Primary Care Provider Ratio,% Disconnected Youth,Average Grade Performance,Average Grade Performance.1,Median Household Income,% Enrolled in Free or Reduced Lunch,Segregation index,Segregation Index,Homicide Rate,Suicide Rate (Age-Adjusted),Firearm Fatalities Rate,Juvenile Arrest Rate,% Homeowners,% Severe Housing Cost Burden,Population,% less than 18 years of age,% 65 and over,% Black,% American Indian & Alaska Native,% Asian,% Native Hawaiian/Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Not Proficient in English,% Female,% Rural,countycode,internet_consumer,internet_nonconsumer,internet_all,internet_hhs,internet_ratio,date,county,state,fips,covid_cases,covid_deaths,internet_percent,q_Years of Potential Life Lost Rate,q_% Fair or Poor Health,q_Average Number of Physically Unhealthy Days,q_Average Number of Mentally Unhealthy Days,q_% Low Birthweight,q_% Smokers,q_% Adults with Obesity,q_Food Environment Index,q_% Physically Inactive,q_% With Access to Exercise Opportunities,q_% Excessive Drinking,q_% Driving Deaths with Alcohol Involvement,q_Chlamydia Rate,q_Teen Birth Rate,q_% Uninsured_x,q_Primary Care Physicians Rate,q_Dentist Rate,q_% With Annual Mammogram,q_% Vaccinated,q_High School Graduation Rate,q_% Some College,q_% Unemployed,q_% Children in Poverty,q_Income Ratio,q_% Single-Parent Households,q_Social Association Rate,q_Violent Crime Rate,q_Injury Death Rate,q_Average Daily PM2.5,q_% Severe Housing Problems,q_% Drive Alone to Work,q_% Long Commute - Drives Alone,q_Life Expectancy,q_Age-Adjusted Death Rate,q_Child Mortality Rate,q_Infant Mortality Rate,q_% Frequent Mental Distress,q_% Adults with Diabetes,q_HIV Prevalence Rate,q_% Food Insecure,q_% Limited Access to Healthy Foods,q_Drug Overdose Mortality Rate,q_Motor Vehicle Mortality Rate,q_% Insufficient Sleep,q_% Uninsured_y,q_% Disconnected Youth,q_Average Grade Performance,q_Average Grade Performance.1,q_Median Household Income,q_% Enrolled in Free or Reduced Lunch,q_Segregation index,q_Segregation Index,q_Homicide Rate,q_Suicide Rate (Age-Adjusted),q_Firearm Fatalities Rate,q_Juvenile Arrest Rate,q_% Homeowners,q_% Severe Housing Cost Burden,q_Population,q_% less than 18 years of age,q_% 65 and over,q_% Not Proficient in English,q_internet_consumer,q_internet_all,q_internet_hhs,q_internet_ratio,q_covid_cases
0,01001,Alabama,Autauga,791.0,8128.591190,20.882987,4.743889,4.654031,8.619529,18.081557,33.3,7.2,34.7,69.130124,15.026031,26.785714,407.2,25.284927,8.721686,45.04180,32.37352,41.0,41.0,90.000000,62.009974,3.629079,19.3,5.234597,26.242679,12.071202,272.282220,68.526994,11.7,No,14.663462,86.523661,39.6,76.879477,417.547551,55.922156,7.940109,14.129347,11.1,219.1,13.2,11.991125,10.809447,19.328751,35.905406,11.148989,2.669154,2527:1,NaN,2.959586,2.802699,59338.0,43.408673,24.619138,23.628395,4.896617,18.145295,16.230078,10.625000,74.894625,13.403481,55601,23.674035,15.562670,19.343177,0.480207,1.224798,0.111509,2.965774,74.308016,0.820225,51.448715,42.002162,1001,16,1,17,21.054,0.75,2020-04-24,Autauga,Alabama,1001,36,2,75.0,0.475367,0.740834,0.849389,0.778217,0.664247,0.584112,0.496046,0.306691,0.892703,0.543165,0.235442,0.477059,0.630594,0.422824,0.387491,0.438551,0.335546,0.497659,0.375585,0.522503,0.633717,0.399353,0.464055,0.855396,0.249101,0.585909,0.629363,0.234590,0.943580,0.624730,0.899676,0.724560,0.435286,0.562139,0.480851,0.745192,0.712797,0.429907,0.731430,0.544393,0.826763,0.118514,0.596711,0.713875,0.438174,NaN,0.354425,0.233288,0.745866,0.287214,0.114931,0.277058,0.481132,0.591068,0.606679,0.162494,0.649533,0.744337,0.671100,0.718907,0.212437,0.526240,0.709382,0.687635,0.672897,0.672717,0.624012
1,01003,Alabama,Baldwin,2967.0,7354.122530,17.509134,4.224519,4.304056,8.345003,17.489033,31.0,8.0,26.5,73.713549,17.958310,30.769231,325.0,27.880692,11.333404,72.89727,49.53629,43.0,44.0,86.361577,67.371620,3.615382,13.9,4.417767,24.139601,10.205617,203.660396,72.385054,10.3,No,13.566201,84.282433,41.7,78.450258,353.343111,47.381750,5.546701,13.475336,10.7,166.5,11.6,5.424427,13.610487,15.811239,33.305868,14.348525,3.538763,1787:1,8.476795,3.005642,2.860696,57588.0,48.486565,41.271763,31.825343,3.008333,19.377511,14.093514,26.192661,73.619343,11.725808,218022,21.607911,20.443350,8.783976,0.772399,1.150343,0.066966,4.646779,83.111337,0.543517,51.538377,42.279099,1003,70,9,80,76.133,0.92,2020-04-24,Baldwin,Alabama,1003,147,3,92.0,0.354645,0.508627,0.646657,0.567937,0.610889,0.529475,0.338785,0.645570,0.445723,0.617626,0.550683,0.628974,0.469552,0.489027,0.569734,0.758685,0.609882,0.607670,0.492438,0.311379,0.786844,0.393602,0.237419,0.501079,0.179727,0.418045,0.471927,0.295867,0.700904,0.503954,0.756203,0.772744,0.638106,0.344653,0.284043,0.307692,0.591661,0.383178,0.629991,0.348490,0.432188,0.242335,0.436570,0.492451,0.615025,0.569311,0.419912,0.293405,0.707764,0.395201,0.394401,0.543445,0.227201,0.675131,0.461503,0.588656,0.573688,0.588278,0.890726,0.429547,0.696981,0.393961,0.912473,0.904385,0.886772,0.934400,0.827103
2,01005,Alabama,Barbour,472.0,10253.573403,29.591802,5.430279,5.185594,11.474559,21.999985,41.7,5.6,23.5,53.166770,12.844016,40.000000,716.3,40.870815,12.242792,31.65809,36.17218,45.0,37.0,81.410256,34.857649,5.171384,43.9,5.681410,56.603426,7.518797,414.277861,70.274612,11.5,No,14.583333,83.368470,32.2,75.341935,497.350062,74.225274,NaN,16.586252,17.6,420.6,22.0,10.739667,NaN,22.854780,38.563167,16.085834,2.913534,1914:1,13.339302,2.660388,2.443271,34382.0,63.292302,25.039132,23.449713,7.618260,12.836104,17.761715,15.000000,61.397779,14.059546,24881,20.867328,19.420441,48.032635,0.659137,0.454162,0.184880,4.276355,45.641252,1.631683,47.216752,67.789635,1005,5,1,6,9.191,0.54,2020-04-24,Barbour,Alabama,1005,32,0,54.0,0.773975,0.981668,0.971603,0.956147,0.925590,0.893961,0.953630,0.048101,0.253055,0.291007,0.069015,0.859285,0.893250,0.790051,0.634436,0.230482,0.402655,0.707058,0.238207,0.129345,0.020129,0.814522,0.983465,0.928058,0.971603,0.187275,0.824734,0.261784,0.916637,0.617182,0.671701,0.521395,0.231381,0.789740,0.777128,NaN,0.961898,0.899173,0.908078,0.969626,0.785533,NaN,0.731010,0.901510,0.710640,0.851742,0.090708,0.047106,0.037383,0.732283,0.121807,0.274009,0.722484,0.196585,0.699907,0.284108,0.109993,0.791802,0.425593,0.330697,0.588066,0.705607,0.391625,0.401510,0.416247,0.192308,0.602265
3,01007,Alabama,Bibb,471.0,11977.539484,19.439724,4.591482,4.551699,10.308710,19.114200,37.6,7.8,33.5,16.251364,15.570042,27.586207,339.7,41.696794,10.206253,48.52656,22.32143,40.0,38.0,83.763838,44.137353,3.971828,27.8,4.368581,28.689236,8.381860,89.349126,108.156028,11.2,No,10.496454,84.910647,49.8,73.571820,589.041117,85.800086,12.244898,14.017536,14.5,196.8,14.3,2.601627,28.060433,25.964321,38.148865,13.000000,2.617801,896:1,NaN,2.628688,2.381308,46064.0,61.562116,52.603794,52.600206,8.232590,20.858766,23.936170,NaN,75.073099,9.886874,22400,20.477679,16.473214,21.120536,0.437500,0.236607,0.116071,2.625000,74.589286,0.268210,46.781250,68.352607,1007,-9999,-9999,4,6.916,-9999.00,2020-04-24,Bibb,Alabama,1007,34,0,-999900.0,0.916886,0.645579,0.797628,0.719986,0.864247,0.684759,0.805356,0.551175,0.854242,0.035971,0.282531,0.502168,0.501467,0.803950,0.492451,0.491969,0.164454,0.439323,0.266835,0.202525,0.124730,0.516535,0.791337,0.465108,0.348311,0.249820,0.133536,0.858593,0.869439,0.173616,0.801510,0.913700,0.081345,0.946532,0.880319,0.977564,0.691948,0.738857,0.696611,0.662114,0.175769,0.754127,0.823023,0.879942,0.540978,NaN,0.078761,0.033199,0.317757,0.697413,0.661100,0.944741,0.753931,0.752189,0.910946,NaN,0.656722,0.353830,0.391086,0.292236,0.286844,0.218188,0.028756,0.278397,0.312365,0.028756,0.613228
4,01009,Alabama,Blount,1085.0,11335.071134,21.745293,4.860808,4.891455,7.604563,19.208672,33.8,8.4,30.3,15.634486,14.230594,19.444444,234.4,33.534595,13.360759,22.40877,19.01798,34.0,39.0,93.468795,53.361073,3.511157,18.0,4.430262,28.561828,8.446383,482.690611,107.285369,11.7,No,10.548012,86.178362,59.4,74.145826,515.611823,83.798883,6.841993,14.859271,17.0,99.8,10.7,2.880150,24.199543,28.666962,35.945010,17.082342,4.077284,4449:1,18.941594,3.025407,2.849339,50412.0,52.906287,48.214823,17.694495,6.425353,17.062628,20.072746,7.460317,78.626214,8.462257,57840,23.153527,18.236515,1.462656,0.653527,0.319848,0.121024,9.571231,86.886238,1.724520,50.726141,89.951502,1009,13,1,14,20.690,0.62,2020-04-24,Blount,Alabama,1009,31,0,62.0,0.877398,0.792595,0.882099,0.884256,0.437024,0.693386,0.535945,0.818987,0.701653,0.035252,0.169303,0.235188,0.247616,0.635699,0.709202,0.125140,0.125000,0.168527,0.299244,0.755214,0.358375,0.353343,0.414450,0.507554,0.342200,0.255931,0.888088,0.850616,0.943580,0.178289,0.881338,0.982920,0.130513,0.828396,0.861702,0.575321,0.819914,0.877965,0.384401,0.252696,0.197468,0.652712,0.877056,0.717110,0.746945,0.963677,0.446018,0.277703,0.478433,0.503562,0.559430,0.147866,0.640723,0.505254,0.798237,0.078692,0.842919,0.171881,0.681524,0.649892,0.466930,0.721064,0.661215,0.640367,0.668584,0.328361,0.595615

**notes:** need to add functionality to include covid deaths (look at nan values)

## Create scores
All scores are on a scale of 1-100 based on county's percentile ranking for a variety of factors. Below, we define several sample scores for different use cases. The user could also build their own score calculator.

In [92]:
# make a new dataframe to store our scores
scores=data[['FIPS','State','County']].copy()

In [93]:
scores.head()

    FIPS    State   County
0  01001  Alabama  Autauga
1  01003  Alabama  Baldwin
2  01005  Alabama  Barbour
3  01007  Alabama     Bibb
4  01009  Alabama   Blount

**COVID vulnerability severe cases**: cases, life lost rate, fair or poor health, smokers, obesity, diabetes, %65 and older,

In [108]:
# describes likelihood that constituents develop severe complications from covid
scores['severe_cases']=((3*data_q['q_covid_cases']+data_q['q_Years of Potential Life Lost Rate']+
                        data_q['q_% Fair or Poor Health']+data_q['q_% Smokers']+
                         data_q['q_% Adults with Obesity']+data_q['q_% Adults with Diabetes']+
                        data_q['q_% 65 and over'])/9)*100

In [104]:
scores.head()

    FIPS    State   County  severe_cases
0  01001  Alabama  Autauga     53.452632
1  01003  Alabama  Baldwin     58.811092
2  01005  Alabama  Barbour     76.636309
3  01007  Alabama     Bibb     65.755160
4  01009  Alabama   Blount     67.011822

**overall poor physical health**:

**COVID vulnerability: health system**: uninsured, provider rates

**Health system access**: mamomgrams, uninsured, provider rates, vaccinations,

**Food services**: free lunch, food insecure, food environment index, limited access to health foods, enrolled in free lunch

In [106]:
# describes existing need for food-based community efforts and non-profits
scores['food_services']=((data_q['q_Food Environment Index']+2*data_q['q_% Food Insecure']+
                         data_q['q_% Limited Access to Healthy Foods']+
                          2*data_q['q_% Enrolled in Free or Reduced Lunch'])/6)*100

In [107]:
scores.head()

    FIPS    State   County  severe_cases  food_services
0  01001  Alabama  Autauga     53.452632      46.611119
1  01003  Alabama  Baldwin     58.811092      42.752325
2  01005  Alabama  Barbour     76.636309      70.624233
3  01007  Alabama     Bibb     65.755160      57.433279
4  01009  Alabama   Blount     67.011822      42.149527

**disparate economic harm**: unemployed, %children in poverty, income ratio, single parents, severe housing problems,
disconnected youth, hs grad rate, enrolled in free lunch, severe housing cost burden, covid cases, uninsured

In [113]:
# describes the likelihood that a community will experience disparate economic harm due to COVID complications
scores['economic']=((3*data_q['q_% Unemployed']+3*data_q['q_% Children in Poverty']+
                     data_q['q_Income Ratio']+2*data_q['q_% Single-Parent Households']+
                    data_q['q_% Severe Housing Problems']+
                    data_q['q_High School Graduation Rate']+2*data_q['q_% Enrolled in Free or Reduced Lunch']
                    +3*data_q['q_% Severe Housing Cost Burden']+data_q['q_covid_cases']+
                    data_q['q_% Uninsured_x'])/19)*100

In [114]:
scores.head()

    FIPS    State   County  severe_cases  food_services   economic
0  01001  Alabama  Autauga     53.452632      46.611119  46.894710
1  01003  Alabama  Baldwin     58.811092      42.752325  39.584208
2  01005  Alabama  Barbour     76.636309      70.624233  74.149598
3  01007  Alabama     Bibb     65.755160      57.433279  47.491998
4  01009  Alabama   Blount     67.011822      42.149527  38.191675

**community connectedness**: single parents, social association, drive alone to work, disconnected youth, segregation index

In [115]:
#describes the likelihood that an area could benefit from community connecting services
scores['community']=((data_q['q_% Single-Parent Households']+3*(1-data_q['q_Social Association Rate'])+
                      data_q['q_% Long Commute - Drives Alone']+data_q['q_% Drive Alone to Work']+
                     data_q['q_Segregation Index'])/7)*100

In [116]:
scores.head()

    FIPS    State   County  severe_cases  food_services   economic  community
0  01001  Alabama  Autauga     53.452632      46.611119  46.894710  48.466670
1  01003  Alabama  Baldwin     58.811092      42.752325  39.584208  57.114066
2  01005  Alabama  Barbour     76.636309      70.624233  74.149598  69.669747
3  01007  Alabama     Bibb     65.755160      57.433279  47.491998  75.125728
4  01009  Alabama   Blount     67.011822      42.149527  38.191675  65.521860

**mental health apps:** frequent mental distress, disconnected youth, average mentally unhealthy days, suicide rate

In [117]:
#describes existing need for additional mental health support 
scores['mental_health']=((2*data_q['q_Average Number of Mentally Unhealthy Days']+
                         data_q['q_% Excessive Drinking']+2*(1-data_q['q_Social Association Rate'])+
                          2*data_q['q_% Frequent Mental Distress']+2*data_q['q_Suicide Rate (Age-Adjusted)'])/9)*100

In [118]:
scores.head()

,FIPS,State,County,severe_cases,food_services,economic,community,mental_health
0,01001,Alabama,Autauga,53.452632,46.611119,46.894710,48.466670,58.086525
1,01003,Alabama,Baldwin,58.811092,42.752325,39.584208,57.114066,59.822793
2,01005,Alabama,Barbour,76.636309,70.624233,74.149598,69.669747,65.819149
3,01007,Alabama,Bibb,65.755160,57.433279,47.491998,75.125728,67.901511
4,01009,Alabama,Blount,67.011822,42.149527,38.191675,65.521860,67.514310

**mobile health needs:** uninsured, smokers, obesity, fair or poor health, PCP rate, internet ratio, smokers, obesity, diabetes, %65 and older

In [120]:
#describes the likelihood that a community could benefit from mobile health services
scores['mobile_health']=((3*data_q['q_% Uninsured_x']+data_q['q_% Smokers']+
                          data_q['q_% Adults with Obesity']+2*data_q['q_% Adults with Diabetes']+
                        2*data_q['q_% 65 and over']+3*(1-data_q['q_Primary Care Physicians Rate'])+
                         2*data_q['q_% Fair or Poor Health']+3*(1-data_q['q_internet_ratio']))/17)*100

In [121]:
scores.head()

,FIPS,State,County,severe_cases,food_services,economic,community,mental_health,mobile_health
0,01001,Alabama,Autauga,53.452632,46.611119,46.894710,48.466670,58.086525,45.148130
1,01003,Alabama,Baldwin,58.811092,42.752325,39.584208,57.114066,59.822793,39.269282
2,01005,Alabama,Barbour,76.636309,70.624233,74.149598,69.669747,65.819149,78.943203
3,01007,Alabama,Bibb,65.755160,57.433279,47.491998,75.125728,67.901511,63.222671
4,01009,Alabama,Blount,67.011822,42.149527,38.191675,65.521860,67.514310,72.184803

**overwhelming health system:** low birthweight, smokers, obesity, fair or poor health, excessive drinking, driving deaths with alcohol, PCP rate, violent crime rate, injury death rate, hiv prevalence, drug overdose, motor vehicle mortality, suicide rate

In [135]:
#describes the likelihood that the existing health infrastructure will be overwhelmed by a covid outbreak
scores['overwhelm']=((data_q['q_% Smokers']+data_q['q_% Adults with Obesity']+2*data_q['q_% Adults with Diabetes']
                        +2*data_q['q_% 65 and over']+data_q['q_% Low Birthweight']
                        +2*data_q['q_% Fair or Poor Health']+data_q['q_% Excessive Drinking']
                        +3*(1-data_q['q_Primary Care Physicians Rate'])+data_q['q_Violent Crime Rate']
                        +data_q['q_Injury Death Rate']+data_q['q_HIV Prevalence Rate']
                         +data_q['q_Motor Vehicle Mortality Rate']
                     )/18)*100

In [136]:
scores.head()

,FIPS,State,County,severe_cases,food_services,economic,community,mental_health,mobile_health,overwhelm
0,01001,Alabama,Autauga,53.452632,46.611119,46.894710,48.466670,58.086525,45.148130,47.903579
1,01003,Alabama,Baldwin,58.811092,42.752325,39.584208,57.114066,59.822793,39.269282,43.142788
2,01005,Alabama,Barbour,76.636309,70.624233,74.149598,69.669747,65.819149,78.943203,71.189844
3,01007,Alabama,Bibb,65.755160,57.433279,47.491998,75.125728,67.901511,63.222671,55.640602
4,01009,Alabama,Blount,67.011822,42.149527,38.191675,65.521860,67.514310,72.184803,65.196559

**information desert:** not profiient in english, community association, internet ratio

In [137]:
# desribes the likelihood that constituents have difficulty accessing reliable covid-19 data
scores['info']=((data_q['q_% Not Proficient in English']+(1-data_q['q_Social Association Rate'])
                +2*data_q['q_internet_ratio'])/4)*100

In [138]:
scores.head()

,FIPS,State,County,severe_cases,food_services,economic,community,mental_health,mobile_health,overwhelm,info
0,01001,Alabama,Autauga,53.452632,46.611119,46.894710,48.466670,58.086525,45.148130,47.903579,57.144141
1,01003,Alabama,Baldwin,58.811092,42.752325,39.584208,57.114066,59.822793,39.269282,43.142788,71.117901
2,01005,Alabama,Barbour,76.636309,70.624233,74.149598,69.669747,65.819149,78.943203,71.189844,47.573688
3,01007,Alabama,Bibb,65.755160,57.433279,47.491998,75.125728,67.901511,63.222671,55.640602,25.647017
4,01009,Alabama,Blount,67.011822,42.149527,38.191675,65.521860,67.514310,72.184803,65.196559,53.046370

**Platform extensions:**
- users can add their own layers (data or calculated)
- we can create better scores with ML
- add functionality to incorporate things that don't exist for every county

In [141]:
#save the scores
scores.to_csv('data/scores.csv', index=False)

In [142]:
penn=scores.loc[scores['State']=='Pennsylvania']
penn.head()

,FIPS,State,County,severe_cases,food_services,economic,community,mental_health,mobile_health,overwhelm,info
1988,42001,Pennsylvania,Adams,53.885747,29.727142,27.310149,49.920196,44.614176,35.818922,NaN,67.370597
1989,42003,Pennsylvania,Allegheny,54.386261,43.479772,48.303841,49.227365,37.305789,19.144956,NaN,65.339684
1990,42005,Pennsylvania,Armstrong,66.967145,53.106917,42.223497,42.543371,48.049557,48.800939,NaN,36.843997
1991,42007,Pennsylvania,Beaver,68.263075,46.860358,39.881202,48.938616,42.132554,42.931960,NaN,48.930625
1992,42009,Pennsylvania,Bedford,49.135483,39.546506,36.526387,27.370344,48.899012,48.037725,NaN,43.475917

In [143]:
penn.to_csv('data/penn_scores.csv', index=False)